## numpy
- n 차원 배열 (ndarray)

In [0]:
import numpy as np

In [0]:
list = [1, 2, 10]
print(list * 3)

[1, 2, 10, 1, 2, 10, 1, 2, 10]


In [0]:
arr = np.array(list)
print(arr * 3)

[ 3  6 30]


In [0]:
# 2차원 리스트로부터 2차원 배열을 만드는 예
data = [[1,2,3],[4,5,6],[7,8,9]]
print(data)
type(data)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [0]:

arr = np.array(data) # list를 ndarray로
print(arr)
type(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [0]:
# 배열의 각 항목의 타입을 알아보려면 dtype 속성값을 보면 된다
arr.dtype

dtype('int64')

In [0]:
# 배열의 구조를 보려면 shape 속성을 보면 된다
arr.shape

(3, 3)

In [0]:
arr[1,2], arr[1][2]

(6, 6)

In [0]:
arr[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
# 초기값이 0인 배열을 만드는 법
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [0]:
# 레인지(범위)를 만드는 법
x = range(5)
print(type(x)) ; x

<class 'range'>


range(0, 5)

In [0]:
# 레인지 형태로 배열을 만드는 법
y = np.arange(5)
print(type(y)) ; y

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [0]:
x[2], y[2]

(2, 2)

In [0]:
# 데이터의 타입을 변경하려면 astype을 사용한다
z = y.astype(np.float32) ; z

array([0., 1., 2., 3., 4.], dtype=float32)

In [0]:
# 벡터화: 배열에 상수를 곱하거나 더할 수 있다
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [0]:
arr + 1000

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

In [0]:
# 배열을 곱하면 각 항목별로 곱셈을 한다
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [0]:
# 전체는 ':'로 표시할 수 있다
arr[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
# 0~11 값을 얻고 이를 4x3 배열로 재구성한다
data = np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
# 5 보다 큰 값을 모두 5로 교체하는 방법
data[data > 5] = 5
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [0]:
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
data.mean()

5.5

In [0]:
data[0]

array([0, 1, 2])

In [0]:
data[[0]]

array([[0, 1, 2]])

In [0]:
data[[1,0]]

array([[3, 4, 5],
       [0, 1, 2]])

In [0]:
# 행의 순서를 임의의 순으로 바꿀 수 있다
# 팬시 색인으로 배열을 바꾸면 본사본이 생기며 원래의 내용을 바지 않는다
data[[3,2,0,1]]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [0]:
data
# data 내용은 그대로 남아 있다

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
# 행과 열을 모두 바꾸려면 아래와 같이 한다
data[[3,2,1,0]][:,[2,1,0]]

array([[11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

In [0]:
# 트랜스포즈는 행과 열의 위치를 바꾸는 것이다
data.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [0]:
# 배열의 곱셈은 np.dot()을 사용한다
np.dot(data,data.T)

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [0]:
# 각 행에 대해서 평균을 구한다 axis=1이면 행을 지칭한다
data.mean(axis=1)

array([ 1.,  4.,  7., 10.])

In [0]:
# axis를 생략해도 된다
data.mean(1)

array([ 1.,  4.,  7., 10.])

In [0]:
# 각 열에 대해서 평균을 구한다 axis=0이면 열을 지칭한다
data.mean(0)

array([4.5, 5.5, 6.5])

In [0]:
# 불리언 연산, True는 1로 False는 0으로 숫자로 치환하여 계산가능하다
1 + True

2

In [0]:
# 배열에서 값이 특정 수보다 큰 원소의 갯수를 반환한다.
x = np.array([1,2,3,4,5,6])
(x>4).sum()

2

In [0]:
(data>1).sum()

10

In [0]:
(x>4)

array([False, False, False, False,  True,  True], dtype=bool)

In [0]:
z = np.random.randint(0,100, 10) ; z

array([82,  1, 38, 46, 35, 50, 94, 22, 87, 91])

In [0]:
z.sort() ; z

array([ 1, 22, 35, 38, 46, 50, 82, 87, 91, 94])

In [0]:
t = np.array([[8,4,11,5],[2,10,7,3],[9,12,1,6]])
t

array([[ 8,  4, 11,  5],
       [ 2, 10,  7,  3],
       [ 9, 12,  1,  6]])

In [0]:
# 열을 기준으로 소팅
t.sort(0) ; t

array([[ 2,  4,  1,  3],
       [ 8, 10,  7,  5],
       [ 9, 12, 11,  6]])

In [0]:
# 행에서 소팅
t.sort(1) ; t

array([[ 1,  2,  3,  4],
       [ 5,  7,  8, 10],
       [ 6,  9, 11, 12]])

In [0]:
t

array([[ 1,  2,  3,  4],
       [ 5,  7,  8, 10],
       [ 6,  9, 11, 12]])

In [0]:
# 순서를 임의로 바꾸는 방법
z = np.arange(10) ; z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.random.permutation(z)

array([8, 2, 9, 1, 7, 4, 0, 3, 5, 6])